### ISSUE TITLE
Standalone mode

### ISSUE THREAD

**Issue by Mikaela** [prey/prey-android-client#30]
It would be nice if Prey for Android had the standalone mode too. I have the check pages of my other devices on GitHub pages and it would be easier to manage all devices if they all were at same place.

**Comment by fanuneza** [comment]
Hi, guys.

This is closely related to this question: https://github.com/prey/prey-android-client/issues/29

Short answer: Prey for Android wouldn't work because you need push notifications via Google Cloud Messaging in order to use it.

**Comment by kampka** [comment]
@fanuneza 
I disagree. Google Cloud Messaging is not something that is uniquely granted to only Fork, Ltd or the Prey project. It relies on shared secrets that any one entity may apply for.
Connecting the Prey client and a standalone server over GCM is simply a matter of configuration, if you supported that. Therefore, your reason for closing this issue is invalid.

**Comment by fanuneza** [comment]
@kampka: Fair enough. I'll leave this feature request open, then. I can't guarantee that it will be addressed anytime soon, but it will be considered. Thanks for your insight :smile:
